#!/bin/bash

# based on https://zenn.dev/yhay81/articles/yhay81-202102-piplock

#cd $(realpath $(dirname $0)/..)

VENV_DIR=.venv_temp_$(date +%s)
python3 -m venv $VENV_DIR
source $VENV_DIR/bin/activate
pip3 install -U pip wheel
pip3 install -r requirements.txt
(
echo "# auto generated by update-pip-lock.sh"
pip3 freeze
) >| requirements.lock
rm -rf $VENV_DIR
